server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5432/user_app
    username: postgres
    password: postgres
    baseline-on-migrate: true
    locations: classpath:db/migration

  redis:
    host: localhost
    port: 6379

jwt:
  secret: "giperbaba8key5ultra7secret2nobody999knows12345"
  access-expiration-ms: 3600000
  refresh-expiration-ms: 86400000

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.userapp: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG


